_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 16
                - 55
            "4": 3.12.10
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
amplitud:
    value: 3
m:
    value: 2
"n":
    value: 2
